# Auto reload modules

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import module.transformations as trans
import pandas as pd
import fs

# Directories

In [3]:
CSV_DIR = fs.open_fs("../data/processed")
DIR_LOG = CSV_DIR.opendir("logs")
DIR_TLG1889 = CSV_DIR.opendir("TLG1889")
DIR_TLG1893 = CSV_DIR.opendir("TLG1893")
DIR_TLG1895 = CSV_DIR.opendir("TLG1895")
DIR_TLG1897 = CSV_DIR.opendir("TLG1897")
DIR_TLG1904 = CSV_DIR.opendir("TLG1904")

In [4]:
DIR_TLG1889_stream = DIR_TLG1889.getsyspath("TLG1889_stream.csv")
DIR_TLG1893_stream = DIR_TLG1893.getsyspath("TLG1893_stream.csv")
DIR_TLG1895_stream = DIR_TLG1895.getsyspath("TLG1895_stream.csv")
DIR_TLG1897_stream = DIR_TLG1897.getsyspath("TLG1897_stream.csv")
DIR_TLG1904_stream = DIR_TLG1904.getsyspath("TLG1904_stream.csv")

In [5]:
df_log = pd.read_csv(DIR_LOG.getsyspath("log.csv"))
df_log

,ObjectId,Name,DisabledState,Location,TimePeriod,StorageMode,SegmentTimePeriod,BackupStrategy,SegmentStartingTime,MaxSize,SegmentMaxSize,ProductSource,Version,PrimaryBackupPath,SecondaryBackupPath,StartTime,EndTime,table_name
0,1889,HMI_RT_5::Descarga,0,D:\DataBase,103680000000000,0,6048000000000,0,132406029160000000,1000,100,NaN,0,NaN,NaN,2021-09-28 23:18:52.000,NaN,Descarga
1,1893,HMI_RT_5::Transferencia,0,D:\DataBase,103680000000000,0,6048000000000,0,132406029210000000,1000,100,NaN,0,NaN,NaN,2021-09-28 23:18:52.000,NaN,Transferencia
2,1895,HMI_RT_5::Recupero,0,D:\DataBase,103680000000000,0,6048000000000,0,132406029230000000,1000,100,NaN,0,NaN,NaN,2021-09-28 23:18:52.000,NaN,Recupero
3,1897,HMI_RT_5::CIP,0,D:\DataBase,103680000000000,0,6048000000000,0,132406029310000000,1000,100,NaN,0,NaN,NaN,2021-09-28 23:18:52.000,NaN,CIP
4,1904,HMI_RT_5::Planta,0,D:\DataBase,103680000000000,0,6048000000000,0,132406848560000000,1000,100,NaN,0,NaN,NaN,2021-09-28 23:18:52.000,NaN,Planta
5,2315,HMI_RT_5::Barrido,0,D:\DataBase,103680000000000,0,6048000000000,0,132417335850000000,1000,100,NaN,0,NaN,NaN,2021-09-28 23:18:52.000,NaN,Barrido
6,2969,HMI_RT_5::RepTrans,0,D:\DataBase,103680000000000,0,6048000000000,0,132472622670000000,1000,100,NaN,0,NaN,NaN,2021-09-28 23:18:52.000,NaN,RepTrans

In [6]:
df_TLG1889_stream = trans.get_full_steam(DIR_LOG.getsyspath("LoggingTag_notna.csv"), DIR_TLG1889.getsyspath("TLG1889.csv"), 1889)
df_TLG1893_stream = trans.get_full_steam(DIR_LOG.getsyspath("LoggingTag_notna.csv"), DIR_TLG1893.getsyspath("TLG1893.csv"), 1893)
df_TLG1895_stream = trans.get_full_steam(DIR_LOG.getsyspath("LoggingTag_notna.csv"), DIR_TLG1895.getsyspath("TLG1895.csv"), 1895)
df_TLG1897_stream = trans.get_full_steam(DIR_LOG.getsyspath("LoggingTag_notna.csv"), DIR_TLG1897.getsyspath("TLG1897.csv"), 1897)
df_TLG1904_stream = trans.get_full_steam(DIR_LOG.getsyspath("LoggingTag_notna.csv"), DIR_TLG1904.getsyspath("TLG1904.csv"), 1904)

In [7]:
df_TLG1904_stream

,pk_TimeStamp,pk_fk_Id,Quality,Value,pk_Key,tag_name,fk_LogId,DataType
0,132478560561901178,1,192,5.05904,1,FIT-Transferencia,1904.0,10
1,132478560571976221,1,192,3.79428,1,FIT-Transferencia,1904.0,10
2,132478560581985734,1,192,2.52952,1,FIT-Transferencia,1904.0,10
3,132478560591925804,1,192,3.79428,1,FIT-Transferencia,1904.0,10
4,132478560601916092,1,192,2.52952,1,FIT-Transferencia,1904.0,10
...,...,...,...,...,...,...,...,...
15269751,133639031431303549,7,192,60.00000,7,PresionTransferencia,1904.0,10
15269752,133639045815627583,7,0,0.00000,7,PresionTransferencia,1904.0,10
15269753,133639045816149517,7,192,0.00000,7,PresionTransferencia,1904.0,10
15269754,133639051681504284,7,192,60.00000,7,PresionTransferencia,1904.0,10
15269755,133639749606561805,7,192,84.00000,7,PresionTransferencia,1904.0,10

In [8]:
df_TLG1889_stream.to_csv(DIR_TLG1889_stream, encoding='utf-8', index=False)
df_TLG1893_stream.to_csv(DIR_TLG1893_stream, encoding='utf-8', index=False)
df_TLG1895_stream.to_csv(DIR_TLG1895_stream, encoding='utf-8', index=False)
df_TLG1897_stream.to_csv(DIR_TLG1897_stream, encoding='utf-8', index=False)
df_TLG1904_stream.to_csv(DIR_TLG1904_stream, encoding='utf-8', index=False)